USE alx_book_store;

SELECT 
    c.COLUMN_NAME,
    c.DATA_TYPE,
    c.IS_NULLABLE,
    c.COLUMN_DEFAULT,
    c.COLUMN_KEY,
    c.EXTRA,
    k.REFERENCED_TABLE_NAME,
    k.REFERENCED_COLUMN_NAME
FROM INFORMATION_SCHEMA.COLUMNS c
LEFT JOIN INFORMATION_SCHEMA.KEY_COLUMN_USAGE k
    ON c.TABLE_NAME = k.TABLE_NAME 
    AND c.COLUMN_NAME = k.COLUMN_NAME 
    AND k.TABLE_SCHEMA = DATABASE()
    AND k.REFERENCED_TABLE_NAME IS NOT NULL
WHERE c.TABLE_NAME = 'Books' 
    AND c.TABLE_SCHEMA = DATABASE();
